package com.Homely.entity;
// Generated Nov 11, 2020, 12:09:47 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dishorder generated by hbm2java
 */
@Entity
@Table(name = "dishorder", catalog = "homely")
public class Dishorder implements java.io.Serializable {

	private int orderid;
	private Customer customer;
	private Date orderdate;
	private String shippingaddress;
	private String paymentmethod;
	private float ordertotal;
	private String receipientname;
	private String receipientphone;
	private String orderstatus;
	private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

	public Dishorder() {
	}

	public Dishorder(int orderid, Customer customer, Date orderdate, String shippingaddress, String paymentmethod,
			float ordertotal, String receipientname, String receipientphone, String orderstatus) {
		this.orderid = orderid;
		this.customer = customer;
		this.orderdate = orderdate;
		this.shippingaddress = shippingaddress;
		this.paymentmethod = paymentmethod;
		this.ordertotal = ordertotal;
		this.receipientname = receipientname;
		this.receipientphone = receipientphone;
		this.orderstatus = orderstatus;
	}

	public Dishorder(int orderid, Customer customer, Date orderdate, String shippingaddress, String paymentmethod,
			float ordertotal, String receipientname, String receipientphone, String orderstatus,
			Set<Orderdetail> orderdetails) {
		this.orderid = orderid;
		this.customer = customer;
		this.orderdate = orderdate;
		this.shippingaddress = shippingaddress;
		this.paymentmethod = paymentmethod;
		this.ordertotal = ordertotal;
		this.receipientname = receipientname;
		this.receipientphone = receipientphone;
		this.orderstatus = orderstatus;
		this.orderdetails = orderdetails;
	}

	@Id

	@Column(name = "orderid", unique = true, nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerid", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "orderdate", nullable = false, length = 19)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Column(name = "shippingaddress", nullable = false, length = 100)
	public String getShippingaddress() {
		return this.shippingaddress;
	}

	public void setShippingaddress(String shippingaddress) {
		this.shippingaddress = shippingaddress;
	}

	@Column(name = "paymentmethod", nullable = false, length = 45)
	public String getPaymentmethod() {
		return this.paymentmethod;
	}

	public void setPaymentmethod(String paymentmethod) {
		this.paymentmethod = paymentmethod;
	}

	@Column(name = "ordertotal", nullable = false, precision = 12, scale = 0)
	public float getOrdertotal() {
		return this.ordertotal;
	}

	public void setOrdertotal(float ordertotal) {
		this.ordertotal = ordertotal;
	}

	@Column(name = "receipientname", nullable = false, length = 45)
	public String getReceipientname() {
		return this.receipientname;
	}

	public void setReceipientname(String receipientname) {
		this.receipientname = receipientname;
	}

	@Column(name = "receipientphone", nullable = false, length = 15)
	public String getReceipientphone() {
		return this.receipientphone;
	}

	public void setReceipientphone(String receipientphone) {
		this.receipientphone = receipientphone;
	}

	@Column(name = "orderstatus", nullable = false, length = 45)
	public String getOrderstatus() {
		return this.orderstatus;
	}

	public void setOrderstatus(String orderstatus) {
		this.orderstatus = orderstatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dishorder")
	public Set<Orderdetail> getOrderdetails() {
		return this.orderdetails;
	}

	public void setOrderdetails(Set<Orderdetail> orderdetails) {
		this.orderdetails = orderdetails;
	}

}
