package com.Homely.entity;
// Generated Nov 11, 2020, 12:09:47 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dish generated by hbm2java
 */
@Entity
@Table(name = "dish", catalog = "homely")
public class Dish implements java.io.Serializable {

	private int dishid;
	private Chef chef;
	private String name;
	private byte[] image;
	private float price;
	private String description;
	private int zipcode;
	private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

	public Dish() {
	}

	public Dish(int dishid, Chef chef, String name, byte[] image, float price, String description, int zipcode) {
		this.dishid = dishid;
		this.chef = chef;
		this.name = name;
		this.image = image;
		this.price = price;
		this.description = description;
		this.zipcode = zipcode;
	}

	public Dish(int dishid, Chef chef, String name, byte[] image, float price, String description, int zipcode,
			Set<Orderdetail> orderdetails) {
		this.dishid = dishid;
		this.chef = chef;
		this.name = name;
		this.image = image;
		this.price = price;
		this.description = description;
		this.zipcode = zipcode;
		this.orderdetails = orderdetails;
	}

	@Id
	@Column(name = "dishid", unique = true, nullable = false)
	public int getDishid() {
		return this.dishid;
	}

	public void setDishid(int dishid) {
		this.dishid = dishid;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "chefid", nullable = false )//
	public Chef getChef() {
		return this.chef;
	}

	public void setChef(Chef chef) {
		this.chef = chef;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "zipcode", nullable = false)
	public int getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(int zipcode) {
		this.zipcode = zipcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dish")
	public Set<Orderdetail> getOrderdetails() {
		return this.orderdetails;
	}

	public void setOrderdetails(Set<Orderdetail> orderdetails) {
		this.orderdetails = orderdetails;
	}

}
